# Generated by Django 5.0.1 on 2024-01-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='sno',
            new_name='id',
        ),
    ]
